version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Europe/Paris
  ignore:
  - dependency-name: rails
    versions:
    - 6.0.3.5
    - 6.1.3
