development:
  host: localhost
  database: softfocus_development

test:
  host: localhost
  database: softfocus_test

production:
  host: localhost
  database: softfocus_production
  username: softfocus
  password: gWhi31D6j74EhdN