development:
  clients:
    default:
      hosts:
        - localhost
      database: softfocus_development

test:
  clients:
    default:
      hosts:
        - localhost
      database: softfocus_test

production:
  clients:
    default:
      database: softfocus_production
      hosts:
        - alpha.rootbox.fr:27017
        - gamma.rootbox.fr:27017
        - omicron.rootbox.fr:27017
      options:
        user: softfocus
        password: gWhi31D6j74EhdN
