development:
  sessions:
    default:
      hosts:
        - localhost
      database: softfocus_development

test:
  sessions:
    default:
      hosts:
        - localhost
      database: softfocus_test

production:
  sessions:
    default:
      database: softfocus_production
      hosts:
        - pi.rootbox.fr:27017
        - lambda.rootbox.fr:27017
        - omicron.rootbox.fr:27017
      username: softfocus
      password: gWhi31D6j74EhdN
      options:
        safe: true
        consistency: :strong
