development:
  clients:
    default:
      hosts: [localhost]
      database: softfocus_development

test:
  clients:
    default:
      hosts: [localhost]
      database: softfocus_test

production:
  clients:
    default:
      hosts: [localhost]
      database: softfocus_production
