# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 712e8dd57b7731eee47446bd90bdc3608ed81c2d347da89020b3d1c7fcb6f5e32f0b52200c7f0f0ed148dac67cf29ec613d858f024803fa921d71ed202c7b178

test:
  secret_key_base: ba0f504146bb2a3072fff01abadeae2dace9f2c082f28c05faabc2ab60281c91886671b1f9e1a08bc3ba43aad233077c5e734f15b0ee187a9d583130500393a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
