# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa37ef66e5ce6c90ade24b8e9116cf242bfaec121a3d31ec5727b70550fd481a7b1313116d4dc281779426f177f85fa76cdca59d85dd74f12fbf7bb8e7947cb7

test:
  secret_key_base: feebbd3c88375ea2bc5f529d6ff03a1d007c4904a83ce87ae54477834b46f8bea7723e0ba00a11fcf14b0676a205147bb8b4c8f70fe968903f6b9d374d529f07

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 7496b767cc9a9380f086205ad3c2c0b78f355e6bdf393551e06397c7f244be4c945826b03801de27414ae5f1fb3b173cf95f24c418361d94ecdebf7b4d126a17
